In [1]:
import torch

In [2]:
"""
    1) Each node v ∈ V aggregates the representations of the nodes in its immediate neighborhood, into a single vector (Note that this aggregation
step depends on the representations generated at the previous iteration of the outer loop and the k = 0 (“base case”) representations are defined as the input node features)
    2) After aggregating the neighboring feature vectors, GraphSAGE then concatenates the node’s current representation with the aggregated neighborhood vector ... torch.cat((node_features, neighbor_features), dim = 1)
    3) This concatenated vector is fed through a fully connected layer with nonlinear activation function σ, which transforms the representations to be used at the next step of the algorithm
"""

'\n    1) Each node v ∈ V aggregates the representations of the nodes in its immediate neighborhood, into a single vector (Note that this aggregation\nstep depends on the representations generated at the previous iteration of the outer loop and the k = 0 (“base case”) representations are defined as the input node features)\n    2) After aggregating the neighboring feature vectors, GraphSAGE then concatenates the node’s current representation with the aggregated neighborhood vector ... torch.cat((node_features, neighbor_features), dim = 1)\n    3) This concatenated vector is fed through a fully connected layer with nonlinear activation function σ, which transforms the representations to be used at the next step of the algorithm\n'

In [41]:
x = torch.rand(5,2, requires_grad = True, dtype = torch.float32)
adj_list = torch.tensor(
                        [[1,2,3,-99],
                         [0,3,-99,-99],
                         [0,3,4,-99],
                         [0,1,2,4],
                         [2,3,-99,-99]]
                         
                         )

In [109]:
def one_degree_hotter(adj_list, already_visited):

    # new_adj_list = torch.ones(adj_list.shape[0], torch.max(adj_list) * torch.max(adj_list))

    for i in range(0, adj_list.shape[0]): 
        cur_nodes = adj_list[i]
        cur_stack = torch.tensor([-99]) 
        for j in cur_nodes:
            if j != -99:
                nodes_to_add_in = adj_list[j]
                for n in nodes_to_add_in:
                    if n not in cur_stack and n not in cur_nodes and n != i and n not in already_visited[i]:
                        cur_stack = torch.cat((cur_stack, n.unsqueeze(0)))
        ready_to_stack = torch.nn.functional.pad(cur_stack, (0, adj_list.shape[0] - cur_stack.shape[0]), value = -99).unsqueeze(0)
        try:
            final_stack = torch.cat((final_stack, ready_to_stack), dim = 0)
        except:
            final_stack = ready_to_stack

    return final_stack


In [110]:
test = one_degree_hotter(adj_list)
test


TypeError: one_degree_hotter() missing 1 required positional argument: 'already_visited'

In [111]:
test2 = one_degree_hotter(test)
test2


TypeError: one_degree_hotter() missing 1 required positional argument: 'already_visited'

In [308]:
class Sage(torch.nn.Module):

    def __init__(self, embed_dim, feature_dim, num_classes, K): 
        super(Sage, self).__init__()
        '''weights is of shape [embed_dim (arbitrary), feature_dim * 2]'''
        self.w1 = torch.nn.Parameter(torch.rand(embed_dim, feature_dim * 2), requires_grad = True)
        self.w2 = torch.nn.Parameter(torch.rand(num_classes, embed_dim), requires_grad = True)
        self.relu = torch.nn.ReLU()
        self.K = K

        self.params  = torch.nn.ParameterDict({})

        new_dim = embed_dim * 4
        for i in range(K):
            # if i == 1:
            # embed_dim = embed_dim
            # feature_dim = feature_dim * 2
            self.params[str(i)] = torch.nn.Parameter(torch.rand(embed_dim, feature_dim * 2), requires_grad = True)
            # else:
            #     self.params[str(i)] = torch.nn.Parameter(torch.rand(embed_dim, feature_dim), requires_grad = True)
            
            # else:
                # embed_dim
                # self.params[str(i)] = torch.nn.Parameter(torch.rand(embed_dim, feature_dim * 2), requires_grad = True)

        print(self.params)


    def forward(self, x, adj_list):

        

        

        already_visited = adj_list

        # print(already_visited)

        for degree in range(self.K):

            # print("DEGREE: ", degree)

            if degree == 0:


                for node in adj_list:
                    cur_neigh_feats = torch.mean(torch.index_select(x, 0, node[node >= 0]), dim = 0).unsqueeze(0)
                    try:
                        neigh_feats = torch.cat((neigh_feats, cur_neigh_feats), dim = 0)
                    except:
                        neigh_feats = cur_neigh_feats

                x = torch.cat((x, neigh_feats), dim = 1)
                x = torch.mm(self.params[str(degree)], x.t())
                x = self.relu(x).t()

            else:

                adj_list = one_degree_hotter(adj_list, already_visited)
                already_visited = torch.cat((already_visited, adj_list), dim = 1)

                for node in adj_list:
                    cur_neigh_feats = torch.mean(torch.index_select(x, 0, node[node >= 0]), dim = 0).unsqueeze(0)
                    try:
                        neigh_feats = torch.cat((neigh_feats, cur_neigh_feats), dim = 0)
                    except:
                        neigh_feats = cur_neigh_feats

                neigh_feats[neigh_feats != neigh_feats] = 0
                

                x = torch.cat((x, neigh_feats), dim = 1)
                x = torch.mm(self.params[str(degree)], x.t())
                x = self.relu(x).t()


            del neigh_feats


        out = torch.mm(self.w2, x).t()

        return out

In [309]:
class sage_net(torch.nn.Module):

    def __init__(self, embed_dim, feature_dim, num_classes, K): 
        super(sage_net, self).__init__()
        self.s = Sage(embed_dim, feature_dim, num_classes, K)
        # self.fc = torch.nn.Linear(4, 1)

    def forward(self, x):

        x, adj_list = x[0], x[1]

        out = self.s(x, adj_list)
        out = torch.mean(out)

        return out

In [310]:
x = torch.tensor([[1.0000, 1.0000, 0.0396, 0.9787],
        [0.5366, 0.5700, 0.1209, 0.5313],
        [0.2313, 0.2818, 0.1446, 0.4948],
        [0.2336, 0.0585, 0.2096, 0.8928]], dtype = torch.float32, requires_grad = True)
y = torch.tensor([345.], dtype = torch.float32, requires_grad = True)

adj_list = torch.tensor([[1,3,-99],
            [0,2,3],
            [1,3,-99],
            [0,1,2]])



In [312]:
model = sage_net(embed_dim = 16, feature_dim = 4, num_classes = 1, K = 10)


ParameterDict(
    (0): Parameter containing: [torch.FloatTensor of size 16x8]
    (1): Parameter containing: [torch.FloatTensor of size 16x8]
    (2): Parameter containing: [torch.FloatTensor of size 16x8]
    (3): Parameter containing: [torch.FloatTensor of size 16x8]
    (4): Parameter containing: [torch.FloatTensor of size 16x8]
    (5): Parameter containing: [torch.FloatTensor of size 16x8]
    (6): Parameter containing: [torch.FloatTensor of size 16x8]
    (7): Parameter containing: [torch.FloatTensor of size 16x8]
    (8): Parameter containing: [torch.FloatTensor of size 16x8]
    (9): Parameter containing: [torch.FloatTensor of size 16x8]
)


In [316]:
model = sage_net(embed_dim = 4, feature_dim = 4, num_classes = 1, K = 10)
criterion = torch.nn.L1Loss()
optimizer = torch.optim.Adam(model.parameters(), lr = 0.01)

input = (x, adj_list)

for i in range(0, 15):

    pred = model(input)

    loss = criterion(pred, y)

    print(loss.item())

    loss.backward()

    optimizer.step()

print(pred)

ParameterDict(
    (0): Parameter containing: [torch.FloatTensor of size 4x8]
    (1): Parameter containing: [torch.FloatTensor of size 4x8]
    (2): Parameter containing: [torch.FloatTensor of size 4x8]
    (3): Parameter containing: [torch.FloatTensor of size 4x8]
    (4): Parameter containing: [torch.FloatTensor of size 4x8]
    (5): Parameter containing: [torch.FloatTensor of size 4x8]
    (6): Parameter containing: [torch.FloatTensor of size 4x8]
    (7): Parameter containing: [torch.FloatTensor of size 4x8]
    (8): Parameter containing: [torch.FloatTensor of size 4x8]
    (9): Parameter containing: [torch.FloatTensor of size 4x8]
)
1072.3824462890625
767.51318359375
528.5009765625
337.11004638671875
183.58929443359375
61.00933837890625
36.14581298828125
112.39837646484375
171.4922637939453
216.7638397216797
250.959716796875
276.40728759765625
295.4537658691406
309.581298828125
319.9632873535156
tensor(25.0367, grad_fn=<MeanBackward0>)


In [46]:
try: del neigh_feats
except: pass


for node in adj_list:
    cur_neigh_feats = torch.mean(torch.index_select(x, 0, node[node > 0]), dim = 0).unsqueeze(0)
    try:
        neigh_feats = torch.cat((neigh_feats, cur_neigh_feats), dim = 0)
    except:
        neigh_feats = cur_neigh_feats

print(neigh_feats)


    

    # print("\n")

tensor([[0.5918, 0.3897],
        [0.6808, 0.2922],
        [0.5245, 0.2379],
        [0.5572, 0.3854],
        [0.6808, 0.2922]])


In [49]:
neigh_feats

tensor([[0.5480, 0.6868],
        [0.3765, 0.5615],
        [0.1179, 0.6393],
        [0.5240, 0.5442],
        [0.3765, 0.5615]])

In [50]:
x

tensor([[0.7804, 0.7554],
        [0.8911, 0.9375],
        [0.5990, 0.2697],
        [0.1539, 0.8532],
        [0.0819, 0.4254]])

In [53]:
cat = torch.cat((x, neigh_feats), dim = 1)
cat

tensor([[0.7804, 0.7554, 0.5480, 0.6868],
        [0.8911, 0.9375, 0.3765, 0.5615],
        [0.5990, 0.2697, 0.1179, 0.6393],
        [0.1539, 0.8532, 0.5240, 0.5442],
        [0.0819, 0.4254, 0.3765, 0.5615]])

In [66]:
cat.t()

tensor([[0.7804, 0.8911, 0.5990, 0.1539, 0.0819],
        [0.7554, 0.9375, 0.2697, 0.8532, 0.4254],
        [0.5480, 0.3765, 0.1179, 0.5240, 0.3765],
        [0.6868, 0.5615, 0.6393, 0.5442, 0.5615]])

In [86]:
l = torch.nn.Linear(4, 1)
l(cat)

tensor([[-0.3884],
        [-0.3401],
        [-0.3273],
        [-0.1176],
        [-0.1519]], grad_fn=<AddmmBackward>)

In [87]:
param = torch.rand(1, 4)
param

tensor([[0.7348, 0.4718, 0.1690, 0.1551]])

In [74]:
param.mm(cat.t())

tensor([[0.8810, 0.8597, 0.5320, 0.7657, 0.5579]])

In [93]:
t1 = torch.rand(128, 2866)
t2 = torch.rand(724, 2866)
# t3 = torch.rand(1)

# torch.cat((t1, t2, t3))

In [94]:
t1

tensor([[0.1119, 0.2839, 0.9802,  ..., 0.1941, 0.5874, 0.9189],
        [0.7242, 0.6031, 0.9000,  ..., 0.2070, 0.0143, 0.3608],
        [0.2858, 0.7533, 0.4856,  ..., 0.2480, 0.1502, 0.6680],
        ...,
        [0.5362, 0.1371, 0.0212,  ..., 0.9871, 0.5192, 0.6612],
        [0.3483, 0.7225, 0.5843,  ..., 0.5180, 0.6524, 0.9938],
        [0.5438, 0.2904, 0.3011,  ..., 0.1303, 0.5327, 0.6136]])

In [95]:
param = torch.rand(1, 2)
param

tensor([[0.0219, 0.1333]])

In [97]:
t1.mm(t2.t()).shape

torch.Size([128, 724])

In [14]:
from collections import defaultdict
# converts from adjacency matrix to adjacency list
def convert(a):
    adjList = defaultdict(list)
    for i in range(len(a)):
        for j in range(len(a[i])):
                       if a[i][j]== 1:
                           adjList[i].append(j)
    return adjList
  
# driver code
a =[[0, 0, 1], [0, 0, 1], [1, 1, 0]] # adjacency matrix
AdjList = convert(a)
print("Adjacency List:")
# print the adjacency list
for i in AdjList:
    print(i, end ="")
    for j in AdjList[i]:
        print(" -> {}".format(j), end ="")
    print()
   

Adjacency List:
0 -> 2
1 -> 2
2 -> 0 -> 1
